-- PostgreSQL equivalent of SQLite rowid for deterministic latest-consent ordering.
ALTER TABLE customer_consent ADD COLUMN consent_seq bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX idx_consent_order ON customer_consent(customer_id, channel, purpose, captured_at DESC, consent_seq DESC);
